In [1]:
import os
import subprocess
import sys
sys.path.append('..')
from tools.qc.scanpy_qc import scanpy_qc
from tools.qc.dropkick_qc import dropkick_qc
from tools.formating.formating import *
import anndata as ad
import pandas as pd
# from tools.run_qc import run_qc

scanpy==1.9.5 anndata==0.9.2 umap==0.5.4 numpy==1.22.4 scipy==1.9.1 pandas==1.3.5 scikit-learn==1.3.1 statsmodels==0.14.0 igraph==0.10.8 pynndescent==0.5.10
scanpy==1.9.5 anndata==0.9.2 umap==0.5.4 numpy==1.22.4 scipy==1.9.1 pandas==1.3.5 scikit-learn==1.3.1 statsmodels==0.14.0 igraph==0.10.8 pynndescent==0.5.10

In [2]:
adata = ad.read_csv('/ps/ai-ready/data/Clustering/Tabula_Muris/FACS/Kidney-counts.csv')
adata

AnnData object with n_obs × n_vars = 23433 × 865

In [3]:
adata.var

Empty DataFrame
Columns: []
Index: [A14.MAA000545.3_8_M.1.1, E1.MAA000545.3_8_M.1.1, M4.MAA000545.3_8_M.1.1, O21.MAA000545.3_8_M.1.1, P4.MAA000545.3_8_M.1.1, A16.MAA000545.3_8_M.1.1, E17.MAA000545.3_8_M.1.1, M5.MAA000545.3_8_M.1.1, A21.MAA000545.3_8_M.1.1, F5.MAA000545.3_8_M.1.1, A18.MAA000545.3_8_M.1.1, F1.MAA000545.3_8_M.1.1, M8.MAA000545.3_8_M.1.1, P5.MAA000545.3_8_M.1.1, M9.MAA000545.3_8_M.1.1, P13.MAA000545.3_8_M.1.1, A22.MAA000545.3_8_M.1.1, F14.MAA000545.3_8_M.1.1, M14.MAA000545.3_8_M.1.1, P18.MAA000545.3_8_M.1.1, B2.MAA000545.3_8_M.1.1, F17.MAA000545.3_8_M.1.1, M18.MAA000545.3_8_M.1.1, P21.MAA000545.3_8_M.1.1, B3.MAA000545.3_8_M.1.1, F22.MAA000545.3_8_M.1.1, M20.MAA000545.3_8_M.1.1, B10.MAA000545.3_8_M.1.1, G1.MAA000545.3_8_M.1.1, M21.MAA000545.3_8_M.1.1, B20.MAA000545.3_8_M.1.1, G6.MAA000545.3_8_M.1.1, N1.MAA000545.3_8_M.1.1, B22.MAA000545.3_8_M.1.1, G11.MAA000545.3_8_M.1.1, N3.MAA000545.3_8_M.1.1, C2.MAA000545.3_8_M.1.1, H2.MAA000545.3_8_M.1.1, N4.MAA000545.3_8_M.1.1, I1.MAA000545.3_8_M.1.1, N5.MAA000545.3_8_M.1.1, C5.MAA000545.3_8_M.1.1, C6.MAA000545.3_8_M.1.1, J1.MAA000545.3_8_M.1.1, N6.MAA000545.3_8_M.1.1, C10.MAA000545.3_8_M.1.1, C12.MAA000545.3_8_M.1.1, K6.MAA000545.3_8_M.1.1, N10.MAA000545.3_8_M.1.1, J7.MAA000545.3_8_M.1.1, N7.MAA000545.3_8_M.1.1, C13.MAA000545.3_8_M.1.1, K7.MAA000545.3_8_M.1.1, N13.MAA000545.3_8_M.1.1, N17.MAA000545.3_8_M.1.1, C18.MAA000545.3_8_M.1.1, K19.MAA000545.3_8_M.1.1, N21.MAA000545.3_8_M.1.1, C22.MAA000545.3_8_M.1.1, L3.MAA000545.3_8_M.1.1, D1.MAA000545.3_8_M.1.1, L6.MAA000545.3_8_M.1.1, O1.MAA000545.3_8_M.1.1, D2.MAA000545.3_8_M.1.1, L8.MAA000545.3_8_M.1.1, O2.MAA000545.3_8_M.1.1, L9.MAA000545.3_8_M.1.1, O4.MAA000545.3_8_M.1.1, A2.MAA000545.3_8_M.1.1, D3.MAA000545.3_8_M.1.1, O6.MAA000545.3_8_M.1.1, A5.MAA000545.3_8_M.1.1, D4.MAA000545.3_8_M.1.1, M1.MAA000545.3_8_M.1.1, M2.MAA000545.3_8_M.1.1, O13.MAA000545.3_8_M.1.1, A6.MAA000545.3_8_M.1.1, D8.MAA000545.3_8_M.1.1, A13.MAA000545.3_8_M.1.1, D18.MAA000545.3_8_M.1.1, M3.MAA000545.3_8_M.1.1, O20.MAA000545.3_8_M.1.1, H21.MAA000752.3_10_M.1.1, M14.MAA000752.3_10_M.1.1, I4.MAA000752.3_10_M.1.1, M15.MAA000752.3_10_M.1.1, O3.MAA000752.3_10_M.1.1, P5.MAA000752.3_10_M.1.1, O2.MAA000752.3_10_M.1.1, P4.MAA000752.3_10_M.1.1, I9.MAA000752.3_10_M.1.1, M18.MAA000752.3_10_M.1.1, O4.MAA000752.3_10_M.1.1, P6.MAA000752.3_10_M.1.1, M19.MAA000752.3_10_M.1.1, O5.MAA000752.3_10_M.1.1, I10.MAA000752.3_10_M.1.1, P7.MAA000752.3_10_M.1.1, I13.MAA000752.3_10_M.1.1, O6.MAA000752.3_10_M.1.1, ...]

[865 rows x 0 columns]

In [4]:
df_ann = pd.read_csv('/ps/ai-ready/data/Clustering/Tabula_Muris/annotations_facs.csv', index_col=None)
df_ann = df_ann.set_index('cell', drop=False)
df_ann

,Neurog3>0_raw,Neurog3>0_scaled,cell,cell_ontology_class,cell_ontology_id,cluster.ids,free_annotation,mouse.id,mouse.sex,plate.barcode,...,subsetC,subsetC_cluster.ids,subsetD,subsetD_cluster.ids,subsetE,subsetE_cluster.ids,subtissue,tissue,tissue_tSNE_1,tissue_tSNE_2
cell,,,,,,,,,,,,,,,,,,,,,
A1.B000610.3_56_F.1.1,NaN,NaN,A1.B000610.3_56_F.1.1,bladder cell,CL:1001319,5,Bladder mesenchymal cell,3_56_F,F,B000610,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bladder,-7.182841,-10.895094
A1.B002764.3_38_F.1.1,NaN,NaN,A1.B002764.3_38_F.1.1,bladder urothelial cell,CL:1001428,3,Luminal bladder epithelial cell,3_38_F,F,B002764,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bladder,4.199059,-11.050240
A1.B002771.3_39_F.1.1,NaN,NaN,A1.B002771.3_39_F.1.1,bladder cell,CL:1001319,5,Bladder mesenchymal cell,3_39_F,F,B002771,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bladder,-11.995435,-7.325534
A1.D041914.3_8_M.1.1,NaN,NaN,A1.D041914.3_8_M.1.1,bladder cell,CL:1001319,5,Bladder mesenchymal cell,3_8_M,M,D041914,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bladder,-6.820022,-14.174246
A1.D042253.3_9_M.1.1,NaN,NaN,A1.D042253.3_9_M.1.1,bladder cell,CL:1001319,2,Bladder mesenchymal cell,3_9_M,M,D042253,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bladder,-24.163538,-7.499349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P22.B002431.3_39_F.1.1,NaN,NaN,P22.B002431.3_39_F.1.1,endothelial cell,CL:0000115,5,NaN,3_39_F,F,B002431,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Aorta,5.520557,6.600335
P22.MAA000906.3_11_M.1.1,NaN,NaN,P22.MAA000906.3_11_M.1.1,endothelial cell,CL:0000115,1,NaN,3_11_M,M,MAA000906,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Aorta,-4.187380,8.307828
P22.MAA000908.3_10_M.1.1,NaN,NaN,P22.MAA000908.3_10_M.1.1,endothelial cell,CL:0000115,1,NaN,3_10_M,M,MAA000908,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Aorta,0.879005,7.568154
P5.MAA000595.3_9_M.1.1,NaN,NaN,P5.MAA000595.3_9_M.1.1,fibroblast,CL:0000057,3,NaN,3_9_M,M,MAA000595,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Aorta,-15.442761,-4.291476
P8.MAA000595.3_9_M.1.1,NaN,NaN,P8.MAA000595.3_9_M.1.1,erythrocyte,CL:0000232,0,NaN,3_9_M,M,MAA000595,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Aorta,10.418298,-6.187611

In [6]:
adata.var = adata.var.join(df_ann)
adata.var

,Neurog3>0_raw,Neurog3>0_scaled,cell,cell_ontology_class,cell_ontology_id,cluster.ids,free_annotation,mouse.id,mouse.sex,plate.barcode,...,subsetC,subsetC_cluster.ids,subsetD,subsetD_cluster.ids,subsetE,subsetE_cluster.ids,subtissue,tissue,tissue_tSNE_1,tissue_tSNE_2
A14.MAA000545.3_8_M.1.1,NaN,NaN,A14.MAA000545.3_8_M.1.1,kidney collecting duct epithelial cell,CL:1000454,4.0,NaN,3_8_M,M,MAA000545,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kidney,16.754983,-3.218600
E1.MAA000545.3_8_M.1.1,NaN,NaN,E1.MAA000545.3_8_M.1.1,epithelial cell of proximal tubule,CL:0002306,2.0,NaN,3_8_M,M,MAA000545,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kidney,-1.452059,8.664250
M4.MAA000545.3_8_M.1.1,NaN,NaN,M4.MAA000545.3_8_M.1.1,kidney collecting duct epithelial cell,CL:1000454,4.0,NaN,3_8_M,M,MAA000545,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kidney,16.651929,-1.860460
O21.MAA000545.3_8_M.1.1,NaN,NaN,O21.MAA000545.3_8_M.1.1,kidney collecting duct epithelial cell,CL:1000454,1.0,NaN,3_8_M,M,MAA000545,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kidney,12.979778,-6.126106
P4.MAA000545.3_8_M.1.1,NaN,NaN,P4.MAA000545.3_8_M.1.1,epithelial cell of proximal tubule,CL:0002306,7.0,NaN,3_8_M,M,MAA000545,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kidney,-0.530594,16.664804
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P4.B002775.3_39_F.1.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
N7.B002775.3_39_F.1.1,NaN,NaN,N7.B002775.3_39_F.1.1,endothelial cell,CL:0000115,0.0,NaN,3_39_F,F,B002775,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kidney,-1.046318,-19.414142
P6.B002775.3_39_F.1.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
N8.B002775.3_39_F.1.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P7.B002775.3_39_F.1.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
adata.obs

Empty DataFrame
Columns: []
Index: [0610005C13Rik, 0610007C21Rik, 0610007L01Rik, 0610007N19Rik, 0610007P08Rik, 0610007P14Rik, 0610007P22Rik, 0610008F07Rik, 0610009B14Rik, 0610009B22Rik, 0610009D07Rik, 0610009L18Rik, 0610009O20Rik, 0610010B08Rik, 0610010F05Rik, 0610010K14Rik, 0610010O12Rik, 0610011F06Rik, 0610011L14Rik, 0610012G03Rik, 0610012H03Rik, 0610030E20Rik, 0610031J06Rik, 0610031O16Rik, 0610037L13Rik, 0610037P05Rik, 0610038B21Rik, 0610038L08Rik, 0610039K10Rik, 0610040B10Rik, 0610040F04Rik, 0610040J01Rik, 0610043K17Rik, 0910001L09Rik, 100043387, 1100001G20Rik, 1110001A16Rik, 1110001J03Rik, 1110002B05Rik, 1110002L01Rik, 1110002N22Rik, 1110003E01Rik, 1110004E09Rik, 1110004F10Rik, 1110005A03Rik, 1110006O24Rik, 1110007C09Rik, 1110008F13Rik, 1110008J03Rik, 1110008L16Rik, 1110008P14Rik, 1110012J17Rik, 1110012L19Rik, 1110014N23Rik, 1110015O18Rik, 1110017D15Rik, 1110017F19Rik, 1110018G07Rik, 1110018J18Rik, 1110019D14Rik, 1110020A21Rik, 1110020G09Rik, 1110021J02Rik, 1110021L09Rik, 1110028C15Rik, 1110028F11Rik, 1110028F18Rik, 1110031I02Rik, 1110032A03Rik, 1110032A04Rik, 1110032F04Rik, 1110034A24Rik, 1110034B05Rik, 1110034G24Rik, 1110035M17Rik, 1110036E04Rik, 1110037F02Rik, 1110038B12Rik, 1110038D17Rik, 1110038F14Rik, 1110046J04Rik, 1110049F12Rik, 1110050K14Rik, 1110051M20Rik, 1110054M08Rik, 1110054O05Rik, 1110057K04Rik, 1110058L19Rik, 1110059E24Rik, 1110059G10Rik, 1110059M19Rik, 1110065P20Rik, 1110067D22Rik, 1190002F15Rik, 1190002H23Rik, 1190002N15Rik, 1190003J15Rik, 1190003K10Rik, 1190005F20Rik, 1190005I06Rik, ...]

[23433 rows x 0 columns]

In [ ]:
adata_merge = pd.merge(adata.var, df_ann, how='left', left_index=True, right_on='cell', sort=False)
adata_merge

In [ ]:
adata1 = ad.read_h5ad('/ps/ai-ready/data/Clustering/Tabula_Sapiens/TS_germ line.h5ad')
adata1

In [ ]:
adata1.var

In [ ]:
adata1.obs